### ISSUE TITLE
Feature Request: better error messages for misconfigured `pack.toml`

### ISSUE THREAD

**Issue by pengolod** [comp500/packwiz#58]
It'd be great if there was better feedback when you've configured your `pack.toml` incorrectly!

With

```toml
name = "Pengolod's Base Modpack"
author = "Pengolod"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b0dad5550b8fc6a9f06ff26b9584f02857bcec62582ed97315eaf0477b22278"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"
acceptable-game-versions = ["1.17"]
```

I got the output

```sh
✗  packwiz refresh
Loading modpack...
toml: cannot load TOML value of type []interface {} into a Go string
```

which I slowly figured out meant that I had put the `acceptable-game-versions` in the wrong object, but it'd be great to get clear feedback :D 

preferably: "`acceptable-game-versions` is not a valid config value for `[versions]`, perhaps you meant 

```toml
[options]
acceptable-game-versions = ["1.17"]
```
?"

thanks for making this great tool btw!
