### ISSUE TITLE
Illegal character for a mod filename

### ISSUE THREAD

**Issue by bolte-io** [comp500/packwiz#77]
Hi,

When trying to launch packwiz with the mixin compability mod included, there is an error with the download.
The error is:

Caused by: java.net.URISyntaxException: Illegal character in path at index 41: https://edge.forgecdn.net/files/3045/381/[___MixinCompat-0.8___].jar

I am guessing it doesn't like the [ or _s?
Can this be fixed at all?

Details of mod:
```toml
name = "Mixin 0.7-0.8 Compatibility"
filename = "[___MixinCompat-0.8___].jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3045/381/[___MixinCompat-0.8___].jar"
hash-format = "murmur2"
hash = "89892035"

[update]
[update.curseforge]
file-id = 3045381
project-id = 405327
```

Thanks
